### PR TITLE
Importing all application sources from Clique repo

### PR DESCRIPTION
**Pull request by waxlamp**

### CODE REVIEW

**Comment by jeffbaumes** [comment]
This is ok, but I'm still unclear why this is more than a config file that contains something like

``` json
{
    "colorby": "type"
}
```

and is instead 5K+ lines of code.

Are many of these files going to be abstracted and placed into core to make this repo much smaller?

**Comment by waxlamp** [comment]
There is probably still some stuff in this repo that can be abstracted and
moved to core, but I would think core should be as small as possible.  In
fact, I view the functional part of core as _just_ the stuff that gets
compiled into clique.min.js.  I would think applications using Clique -
whether this ANB viewer, or even just the "demo mode" that comes with
Clique - would be expected to be "longer", in the sense of all application
logic, HTML templates, etc., surrounding/supporting the use of the library
in Clique itself.

**Comment by waxlamp** [comment]
Put another way - I think a lot of the LOC comes from the Gulp
infrastructure, which was more or less duplicated from core.  This repo
could be compressed considerably by switching to HTML and JS bundled in a
directory, and dumping most or all of the Gulp support.

**Comment by jeffbaumes** [comment]
Ah ok. I saw clique core as also containing compiled templates and JS logic for quickly building clique UIs. Hate to see lots of HTML/Jade/JS copied around. I guess if we use code in more than one app, we should seriously consider putting it into core.

**Comment by waxlamp** [comment]
That is not a bad idea, and I did plan to move some things back into core
if we had the right way to do it.  Maybe we can set up a time to do some
code review.  I think this will be more clear if I can show you a few
things in person.  I'll see if I can find a slot on the calendar.

**Comment by jeffbaumes** [comment]
+1

**Pull request merged**
